"""create master_gender_table

Revision ID: 030b3492967f
Revises: d71f0019253e
Create Date: 2026-06-21 12:48:53.663945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '030b3492967f'
down_revision: Union[str, Sequence[str], None] = 'd71f0019253e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_gender_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accord_key', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accord_key'], ['master_accord_table.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_gender_table_accord_key'), 'master_gender_table', ['accord_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_gender_table_accord_key'), table_name='master_gender_table')
    op.drop_table('master_gender_table')
    # ### end Alembic commands ###
