"""update_master_gender_table_to_three_columns

Revision ID: 03b2e1ae72d5
Revises: 030b3492967f
Create Date: 2026-06-21 12:59:10.188048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b2e1ae72d5'
down_revision: Union[str, Sequence[str], None] = '030b3492967f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_gender_table', sa.Column('unisex_value', sa.Double(), nullable=False))
    op.add_column('master_gender_table', sa.Column('female_value', sa.Double(), nullable=False))
    op.add_column('master_gender_table', sa.Column('male_value', sa.Double(), nullable=False))
    op.drop_column('master_gender_table', 'classification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_gender_table', sa.Column('classification', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('master_gender_table', 'male_value')
    op.drop_column('master_gender_table', 'female_value')
    op.drop_column('master_gender_table', 'unisex_value')
    # ### end Alembic commands ###
