"""create perception stage tables

Revision ID: 0df4262a940d
Revises: 194bde04f38d
Create Date: 2026-05-25 06:13:52.833850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0df4262a940d'
down_revision: Union[str, Sequence[str], None] = '194bde04f38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perception_score_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('p_1', sa.Boolean(), nullable=False),
    sa.Column('p_2', sa.Boolean(), nullable=False),
    sa.Column('p_3', sa.Boolean(), nullable=False),
    sa.Column('p_4', sa.Boolean(), nullable=False),
    sa.Column('p_5', sa.Boolean(), nullable=False),
    sa.Column('p_6', sa.Boolean(), nullable=False),
    sa.Column('p_7', sa.Boolean(), nullable=False),
    sa.Column('p_8', sa.Boolean(), nullable=False),
    sa.Column('p_9', sa.Boolean(), nullable=False),
    sa.Column('p_10', sa.Boolean(), nullable=False),
    sa.Column('p_11', sa.Boolean(), nullable=False),
    sa.Column('p_12', sa.Boolean(), nullable=False),
    sa.Column('p_13', sa.Boolean(), nullable=False),
    sa.Column('p_14', sa.Boolean(), nullable=False),
    sa.Column('p_15', sa.Boolean(), nullable=False),
    sa.Column('p_16', sa.Boolean(), nullable=False),
    sa.Column('p_17', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perception_score_table_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('p_1', sa.Boolean(), nullable=False),
    sa.Column('p_2', sa.Boolean(), nullable=False),
    sa.Column('p_3', sa.Boolean(), nullable=False),
    sa.Column('p_4', sa.Boolean(), nullable=False),
    sa.Column('p_5', sa.Boolean(), nullable=False),
    sa.Column('p_6', sa.Boolean(), nullable=False),
    sa.Column('p_7', sa.Boolean(), nullable=False),
    sa.Column('p_8', sa.Boolean(), nullable=False),
    sa.Column('p_9', sa.Boolean(), nullable=False),
    sa.Column('p_10', sa.Boolean(), nullable=False),
    sa.Column('p_11', sa.Boolean(), nullable=False),
    sa.Column('p_12', sa.Boolean(), nullable=False),
    sa.Column('p_13', sa.Boolean(), nullable=False),
    sa.Column('p_14', sa.Boolean(), nullable=False),
    sa.Column('p_15', sa.Boolean(), nullable=False),
    sa.Column('p_16', sa.Boolean(), nullable=False),
    sa.Column('p_17', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perception_score_table_history')
    op.drop_table('perception_score_table')
    # ### end Alembic commands ###
