"""create master_personality_accord_mapping

Revision ID: 2cc41601e367
Revises: aeb33944706e
Create Date: 2026-06-21 12:33:29.370613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cc41601e367'
down_revision: Union[str, Sequence[str], None] = 'aeb33944706e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_personality_accord_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personality_type', sa.String(), nullable=False),
    sa.Column('accord_key', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accord_key'], ['master_accord_table.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_personality_accord_mapping_accord_key'), 'master_personality_accord_mapping', ['accord_key'], unique=False)
    op.create_index(op.f('ix_master_personality_accord_mapping_personality_type'), 'master_personality_accord_mapping', ['personality_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_personality_accord_mapping_personality_type'), table_name='master_personality_accord_mapping')
    op.drop_index(op.f('ix_master_personality_accord_mapping_accord_key'), table_name='master_personality_accord_mapping')
    op.drop_table('master_personality_accord_mapping')
    # ### end Alembic commands ###
