"""create master climate and mapping tables

Revision ID: 4f6b751ce486
Revises: d54ef1c49cf8
Create Date: 2026-06-21 13:59:45.994956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f6b751ce486'
down_revision: Union[str, Sequence[str], None] = 'd54ef1c49cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_climate_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_climate_table_key'), 'master_climate_table', ['key'], unique=True)
    op.create_index(op.f('ix_master_climate_table_name'), 'master_climate_table', ['name'], unique=True)
    op.create_table('master_climate_accord_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('climate_key', sa.String(), nullable=False),
    sa.Column('accord_key', sa.String(), nullable=False),
    sa.Column('breach_count', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accord_key'], ['master_accord_table.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['climate_key'], ['master_climate_table.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_climate_accord_mapping_accord_key'), 'master_climate_accord_mapping', ['accord_key'], unique=False)
    op.create_index(op.f('ix_master_climate_accord_mapping_climate_key'), 'master_climate_accord_mapping', ['climate_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_climate_accord_mapping_climate_key'), table_name='master_climate_accord_mapping')
    op.drop_index(op.f('ix_master_climate_accord_mapping_accord_key'), table_name='master_climate_accord_mapping')
    op.drop_table('master_climate_accord_mapping')
    op.drop_index(op.f('ix_master_climate_table_name'), table_name='master_climate_table')
    op.drop_index(op.f('ix_master_climate_table_key'), table_name='master_climate_table')
    op.drop_table('master_climate_table')
    # ### end Alembic commands ###
