"""create sensitivity filters table

Revision ID: 61d4e7de2767
Revises: 766bf20dc677
Create Date: 2026-05-22 15:14:35.615384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61d4e7de2767'
down_revision: Union[str, Sequence[str], None] = '766bf20dc677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitivity_filters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('has_migraine_issues', sa.Boolean(), nullable=True),
    sa.Column('has_respiratory_issues', sa.Boolean(), nullable=True),
    sa.Column('has_skin_sensitivity', sa.Boolean(), nullable=True),
    sa.Column('has_strong_smell_discomfort', sa.Boolean(), nullable=True),
    sa.Column('has_body_odour_concern', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensitivity_filters')
    # ### end Alembic commands ###
