"""create pincode city state mapping table

Revision ID: 6feab77e43d4
Revises: f4109253d3b9
Create Date: 2026-07-05 13:12:40.096914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6feab77e43d4'
down_revision: Union[str, Sequence[str], None] = 'f4109253d3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pincode_city_state_mapping_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pincode', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pincode_city_state_mapping_table_pincode'), 'pincode_city_state_mapping_table', ['pincode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pincode_city_state_mapping_table_pincode'), table_name='pincode_city_state_mapping_table')
    op.drop_table('pincode_city_state_mapping_table')
    # ### end Alembic commands ###
