"""create occasion tables

Revision ID: 725ae0fde587
Revises: b3e9034d8ff2
Create Date: 2026-05-25 06:45:59.131008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '725ae0fde587'
down_revision: Union[str, Sequence[str], None] = 'b3e9034d8ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occasion_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('oc_1', sa.Boolean(), nullable=True),
    sa.Column('oc_2', sa.Boolean(), nullable=True),
    sa.Column('oc_3', sa.Boolean(), nullable=True),
    sa.Column('oc_4', sa.Boolean(), nullable=True),
    sa.Column('oc_5', sa.Boolean(), nullable=True),
    sa.Column('oc_6', sa.Boolean(), nullable=True),
    sa.Column('oc_7', sa.Boolean(), nullable=True),
    sa.Column('oc_8', sa.Boolean(), nullable=True),
    sa.Column('oc_9', sa.Boolean(), nullable=True),
    sa.Column('oc_10', sa.Boolean(), nullable=True),
    sa.Column('oc_11', sa.Boolean(), nullable=True),
    sa.Column('oc_12', sa.Boolean(), nullable=True),
    sa.Column('oc_13', sa.Boolean(), nullable=True),
    sa.Column('oc_14', sa.Boolean(), nullable=True),
    sa.Column('oc_15', sa.Boolean(), nullable=True),
    sa.Column('oc_16', sa.Boolean(), nullable=True),
    sa.Column('oc_17', sa.Boolean(), nullable=True),
    sa.Column('oc_18', sa.Boolean(), nullable=True),
    sa.Column('oc_19', sa.Boolean(), nullable=True),
    sa.Column('oc_20', sa.Boolean(), nullable=True),
    sa.Column('oc_21', sa.Boolean(), nullable=True),
    sa.Column('oc_22', sa.Boolean(), nullable=True),
    sa.Column('oc_23', sa.Boolean(), nullable=True),
    sa.Column('oc_24', sa.Boolean(), nullable=True),
    sa.Column('oc_25', sa.Boolean(), nullable=True),
    sa.Column('oc_26', sa.Boolean(), nullable=True),
    sa.Column('oc_27', sa.Boolean(), nullable=True),
    sa.Column('oc_28', sa.Boolean(), nullable=True),
    sa.Column('oc_29', sa.Boolean(), nullable=True),
    sa.Column('oc_30', sa.Boolean(), nullable=True),
    sa.Column('oc_31', sa.Boolean(), nullable=True),
    sa.Column('oc_32', sa.Boolean(), nullable=True),
    sa.Column('oc_33', sa.Boolean(), nullable=True),
    sa.Column('oc_34', sa.Boolean(), nullable=True),
    sa.Column('oc_35', sa.Boolean(), nullable=True),
    sa.Column('oc_36', sa.Boolean(), nullable=True),
    sa.Column('oc_37', sa.Boolean(), nullable=True),
    sa.Column('oc_38', sa.Boolean(), nullable=True),
    sa.Column('oc_39', sa.Boolean(), nullable=True),
    sa.Column('oc_40', sa.Boolean(), nullable=True),
    sa.Column('oc_41', sa.Boolean(), nullable=True),
    sa.Column('oc_42', sa.Boolean(), nullable=True),
    sa.Column('oc_43', sa.Boolean(), nullable=True),
    sa.Column('oc_44', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occasion_table_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('oc_1', sa.Boolean(), nullable=True),
    sa.Column('oc_2', sa.Boolean(), nullable=True),
    sa.Column('oc_3', sa.Boolean(), nullable=True),
    sa.Column('oc_4', sa.Boolean(), nullable=True),
    sa.Column('oc_5', sa.Boolean(), nullable=True),
    sa.Column('oc_6', sa.Boolean(), nullable=True),
    sa.Column('oc_7', sa.Boolean(), nullable=True),
    sa.Column('oc_8', sa.Boolean(), nullable=True),
    sa.Column('oc_9', sa.Boolean(), nullable=True),
    sa.Column('oc_10', sa.Boolean(), nullable=True),
    sa.Column('oc_11', sa.Boolean(), nullable=True),
    sa.Column('oc_12', sa.Boolean(), nullable=True),
    sa.Column('oc_13', sa.Boolean(), nullable=True),
    sa.Column('oc_14', sa.Boolean(), nullable=True),
    sa.Column('oc_15', sa.Boolean(), nullable=True),
    sa.Column('oc_16', sa.Boolean(), nullable=True),
    sa.Column('oc_17', sa.Boolean(), nullable=True),
    sa.Column('oc_18', sa.Boolean(), nullable=True),
    sa.Column('oc_19', sa.Boolean(), nullable=True),
    sa.Column('oc_20', sa.Boolean(), nullable=True),
    sa.Column('oc_21', sa.Boolean(), nullable=True),
    sa.Column('oc_22', sa.Boolean(), nullable=True),
    sa.Column('oc_23', sa.Boolean(), nullable=True),
    sa.Column('oc_24', sa.Boolean(), nullable=True),
    sa.Column('oc_25', sa.Boolean(), nullable=True),
    sa.Column('oc_26', sa.Boolean(), nullable=True),
    sa.Column('oc_27', sa.Boolean(), nullable=True),
    sa.Column('oc_28', sa.Boolean(), nullable=True),
    sa.Column('oc_29', sa.Boolean(), nullable=True),
    sa.Column('oc_30', sa.Boolean(), nullable=True),
    sa.Column('oc_31', sa.Boolean(), nullable=True),
    sa.Column('oc_32', sa.Boolean(), nullable=True),
    sa.Column('oc_33', sa.Boolean(), nullable=True),
    sa.Column('oc_34', sa.Boolean(), nullable=True),
    sa.Column('oc_35', sa.Boolean(), nullable=True),
    sa.Column('oc_36', sa.Boolean(), nullable=True),
    sa.Column('oc_37', sa.Boolean(), nullable=True),
    sa.Column('oc_38', sa.Boolean(), nullable=True),
    sa.Column('oc_39', sa.Boolean(), nullable=True),
    sa.Column('oc_40', sa.Boolean(), nullable=True),
    sa.Column('oc_41', sa.Boolean(), nullable=True),
    sa.Column('oc_42', sa.Boolean(), nullable=True),
    sa.Column('oc_43', sa.Boolean(), nullable=True),
    sa.Column('oc_44', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occasion_table_history')
    op.drop_table('occasion_table')
    # ### end Alembic commands ###
