"""create sensitivity filter history table

Revision ID: 746f29850c66
Revises: 61d4e7de2767
Create Date: 2026-05-22 16:59:54.817551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '746f29850c66'
down_revision: Union[str, Sequence[str], None] = '61d4e7de2767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitivity_filter_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('has_migraine_issues', sa.Boolean(), nullable=True),
    sa.Column('has_respiratory_issues', sa.Boolean(), nullable=True),
    sa.Column('has_skin_sensitivity', sa.Boolean(), nullable=True),
    sa.Column('has_strong_smell_discomfort', sa.Boolean(), nullable=True),
    sa.Column('has_body_odour_concern', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensitivity_filter_history')
    # ### end Alembic commands ###
