"""create pincode zoneid mapping table

Revision ID: 7bf1c2514d3c
Revises: ad48a85008d7
Create Date: 2026-06-09 12:14:39.807273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bf1c2514d3c'
down_revision: Union[str, Sequence[str], None] = 'ad48a85008d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pincode_zoneid_mapping_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['master_zone_table.zone_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pincode_zoneid_mapping_table_pincode'), 'pincode_zoneid_mapping_table', ['pincode'], unique=True)
    op.create_index(op.f('ix_pincode_zoneid_mapping_table_zone_id'), 'pincode_zoneid_mapping_table', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pincode_zoneid_mapping_table_zone_id'), table_name='pincode_zoneid_mapping_table')
    op.drop_index(op.f('ix_pincode_zoneid_mapping_table_pincode'), table_name='pincode_zoneid_mapping_table')
    op.drop_table('pincode_zoneid_mapping_table')
    # ### end Alembic commands ###
