"""add perception p_18_to_p_22

Revision ID: 9e0f0f007131
Revises: 0ecca6652f58
Create Date: 2026-06-18 11:31:30.578843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0f0f007131'
down_revision: Union[str, Sequence[str], None] = '0ecca6652f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perception_score_table', sa.Column('p_18', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table', sa.Column('p_19', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table', sa.Column('p_20', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table', sa.Column('p_21', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table', sa.Column('p_22', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table_history', sa.Column('p_18', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table_history', sa.Column('p_19', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table_history', sa.Column('p_20', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table_history', sa.Column('p_21', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('perception_score_table_history', sa.Column('p_22', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perception_score_table_history', 'p_22')
    op.drop_column('perception_score_table_history', 'p_21')
    op.drop_column('perception_score_table_history', 'p_20')
    op.drop_column('perception_score_table_history', 'p_19')
    op.drop_column('perception_score_table_history', 'p_18')
    op.drop_column('perception_score_table', 'p_22')
    op.drop_column('perception_score_table', 'p_21')
    op.drop_column('perception_score_table', 'p_20')
    op.drop_column('perception_score_table', 'p_19')
    op.drop_column('perception_score_table', 'p_18')
    # ### end Alembic commands ###
