"""create master perception accord mapping table

Revision ID: a4a6c4b05de2
Revises: ba2d75f6d731
Create Date: 2026-06-21 13:36:15.157874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4a6c4b05de2'
down_revision: Union[str, Sequence[str], None] = 'ba2d75f6d731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_perception_accord_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perception_key', sa.String(), nullable=False),
    sa.Column('accord_key', sa.String(), nullable=False),
    sa.Column('score_level', sa.String(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accord_key'], ['master_accord_table.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perception_key'], ['master_perception_table.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_perception_accord_mapping_accord_key'), 'master_perception_accord_mapping', ['accord_key'], unique=False)
    op.create_index(op.f('ix_master_perception_accord_mapping_perception_key'), 'master_perception_accord_mapping', ['perception_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_perception_accord_mapping_perception_key'), table_name='master_perception_accord_mapping')
    op.drop_index(op.f('ix_master_perception_accord_mapping_accord_key'), table_name='master_perception_accord_mapping')
    op.drop_table('master_perception_accord_mapping')
    # ### end Alembic commands ###
