"""create climate zone master table

Revision ID: ad32674184a0
Revises: b2b92c6f21c2
Create Date: 2026-06-01 10:31:31.365275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad32674184a0'
down_revision: Union[str, Sequence[str], None] = 'b2b92c6f21c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_zone_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_zone_table_zone_id'), 'master_zone_table', ['zone_id'], unique=True)
    op.create_index(op.f('ix_master_zone_table_zone_name'), 'master_zone_table', ['zone_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_zone_table_zone_name'), table_name='master_zone_table')
    op.drop_index(op.f('ix_master_zone_table_zone_id'), table_name='master_zone_table')
    op.drop_table('master_zone_table')
    # ### end Alembic commands ###
