"""create  climate zone master climate table

Revision ID: ad48a85008d7
Revises: 0d13b1d51c88
Create Date: 2026-06-01 11:35:23.130437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad48a85008d7'
down_revision: Union[str, Sequence[str], None] = '0d13b1d51c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_zone_climate_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=False),
    sa.Column('avg_temperature', sa.Double(), nullable=False),
    sa.Column('avg_humidity', sa.Double(), nullable=False),
    sa.Column('avg_rainfall', sa.Double(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['master_zone_table.zone_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_zone_climate_table_month_number'), 'master_zone_climate_table', ['month_number'], unique=False)
    op.create_index(op.f('ix_master_zone_climate_table_zone_id'), 'master_zone_climate_table', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_zone_climate_table_zone_id'), table_name='master_zone_climate_table')
    op.drop_index(op.f('ix_master_zone_climate_table_month_number'), table_name='master_zone_climate_table')
    op.drop_table('master_zone_climate_table')
    # ### end Alembic commands ###
