"""create master_accord_table

Revision ID: aeb33944706e
Revises: 9e0f0f007131
Create Date: 2026-06-21 12:22:41.338299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeb33944706e'
down_revision: Union[str, Sequence[str], None] = '9e0f0f007131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_accord_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_accord_table_key'), 'master_accord_table', ['key'], unique=True)
    op.create_index(op.f('ix_master_accord_table_name'), 'master_accord_table', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_accord_table_name'), table_name='master_accord_table')
    op.drop_index(op.f('ix_master_accord_table_key'), table_name='master_accord_table')
    op.drop_table('master_accord_table')
    # ### end Alembic commands ###
