"""create_cart_items_and_price_configs

Revision ID: af2a2a46f229
Revises: ef1ed10347bb
Create Date: 2026-07-09 15:05:40.088938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af2a2a46f229'
down_revision: Union[str, Sequence[str], None] = 'ef1ed10347bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_configs',
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('size')
    )
    
    # Seed default price configs
    op.execute("INSERT INTO price_configs (size, price, created_at, updated_at) VALUES ('50ml', 1200.00, now(), now()), ('100ml', 2000.00, now(), now())")

    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pre_cart_item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pre_cart_item_id'], ['pre_cart_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size'], ['price_configs.size'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cart_activity_traces', sa.Column('pre_cart_item_id', sa.UUID(), nullable=True))
    op.add_column('cart_activity_traces', sa.Column('size', sa.String(), nullable=True))
    op.add_column('cart_activity_traces', sa.Column('old_qty', sa.Integer(), nullable=True))
    op.add_column('cart_activity_traces', sa.Column('new_qty', sa.Integer(), nullable=True))
    op.alter_column('cart_activity_traces', 'combo_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'cart_activity_traces', 'pre_cart_items', ['pre_cart_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart_activity_traces', 'formula_snapshot')
    op.drop_column('cart_activity_traces', 'old_quantity')
    op.drop_column('cart_activity_traces', 'new_quantity')
    op.drop_column('cart_activity_traces', 'recommendation_rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_activity_traces', sa.Column('recommendation_rank', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('cart_activity_traces', sa.Column('new_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart_activity_traces', sa.Column('old_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart_activity_traces', sa.Column('formula_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_activity_traces', type_='foreignkey')
    op.alter_column('cart_activity_traces', 'combo_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('cart_activity_traces', 'new_qty')
    op.drop_column('cart_activity_traces', 'old_qty')
    op.drop_column('cart_activity_traces', 'size')
    op.drop_column('cart_activity_traces', 'pre_cart_item_id')
    op.drop_table('cart_items')
    op.drop_table('price_configs')
    # ### end Alembic commands ###
