"""create personality score tables

Revision ID: b3e9034d8ff2
Revises: 0df4262a940d
Create Date: 2026-05-25 06:29:57.019915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3e9034d8ff2'
down_revision: Union[str, Sequence[str], None] = '0df4262a940d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_score_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('pr_1', sa.Integer(), nullable=False),
    sa.Column('pr_2', sa.Integer(), nullable=False),
    sa.Column('pr_3', sa.Integer(), nullable=False),
    sa.Column('pr_4', sa.Integer(), nullable=False),
    sa.Column('pr_5', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality_score_table_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('pr_1', sa.Integer(), nullable=False),
    sa.Column('pr_2', sa.Integer(), nullable=False),
    sa.Column('pr_3', sa.Integer(), nullable=False),
    sa.Column('pr_4', sa.Integer(), nullable=False),
    sa.Column('pr_5', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personality_score_table_history')
    op.drop_table('personality_score_table')
    # ### end Alembic commands ###
