"""create master perception table

Revision ID: ba2d75f6d731
Revises: 03b2e1ae72d5
Create Date: 2026-06-21 13:15:36.572680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba2d75f6d731'
down_revision: Union[str, Sequence[str], None] = '03b2e1ae72d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_perception_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_perception_table_key'), 'master_perception_table', ['key'], unique=True)
    op.create_index(op.f('ix_master_perception_table_name'), 'master_perception_table', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_perception_table_name'), table_name='master_perception_table')
    op.drop_index(op.f('ix_master_perception_table_key'), table_name='master_perception_table')
    op.drop_table('master_perception_table')
    # ### end Alembic commands ###
