"""create master sensitivity and mapping tables

Revision ID: d54ef1c49cf8
Revises: a4a6c4b05de2
Create Date: 2026-06-21 13:46:54.081037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd54ef1c49cf8'
down_revision: Union[str, Sequence[str], None] = 'a4a6c4b05de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_sensitivity_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_sensitivity_table_key'), 'master_sensitivity_table', ['key'], unique=True)
    op.create_index(op.f('ix_master_sensitivity_table_name'), 'master_sensitivity_table', ['name'], unique=True)
    op.create_table('master_sensitivity_accord_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensitivity_key', sa.String(), nullable=False),
    sa.Column('accord_key', sa.String(), nullable=False),
    sa.Column('is_flagged', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accord_key'], ['master_accord_table.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensitivity_key'], ['master_sensitivity_table.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_sensitivity_accord_mapping_accord_key'), 'master_sensitivity_accord_mapping', ['accord_key'], unique=False)
    op.create_index(op.f('ix_master_sensitivity_accord_mapping_sensitivity_key'), 'master_sensitivity_accord_mapping', ['sensitivity_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_sensitivity_accord_mapping_sensitivity_key'), table_name='master_sensitivity_accord_mapping')
    op.drop_index(op.f('ix_master_sensitivity_accord_mapping_accord_key'), table_name='master_sensitivity_accord_mapping')
    op.drop_table('master_sensitivity_accord_mapping')
    op.drop_index(op.f('ix_master_sensitivity_table_name'), table_name='master_sensitivity_table')
    op.drop_index(op.f('ix_master_sensitivity_table_key'), table_name='master_sensitivity_table')
    op.drop_table('master_sensitivity_table')
    # ### end Alembic commands ###
