"""create master_personality_table_and_update_mapping

Revision ID: d71f0019253e
Revises: 2cc41601e367
Create Date: 2026-06-21 12:38:10.017968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd71f0019253e'
down_revision: Union[str, Sequence[str], None] = '2cc41601e367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_personality_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_personality_table_key'), 'master_personality_table', ['key'], unique=True)
    op.create_index(op.f('ix_master_personality_table_name'), 'master_personality_table', ['name'], unique=True)
    op.add_column('master_personality_accord_mapping', sa.Column('personality_key', sa.String(), nullable=False))
    op.drop_index(op.f('ix_master_personality_accord_mapping_personality_type'), table_name='master_personality_accord_mapping')
    op.create_index(op.f('ix_master_personality_accord_mapping_personality_key'), 'master_personality_accord_mapping', ['personality_key'], unique=False)
    op.create_foreign_key(None, 'master_personality_accord_mapping', 'master_personality_table', ['personality_key'], ['key'], ondelete='CASCADE')
    op.drop_column('master_personality_accord_mapping', 'personality_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_personality_accord_mapping', sa.Column('personality_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'master_personality_accord_mapping', type_='foreignkey')
    op.drop_index(op.f('ix_master_personality_accord_mapping_personality_key'), table_name='master_personality_accord_mapping')
    op.create_index(op.f('ix_master_personality_accord_mapping_personality_type'), 'master_personality_accord_mapping', ['personality_type'], unique=False)
    op.drop_column('master_personality_accord_mapping', 'personality_key')
    op.drop_index(op.f('ix_master_personality_table_name'), table_name='master_personality_table')
    op.drop_index(op.f('ix_master_personality_table_key'), table_name='master_personality_table')
    op.drop_table('master_personality_table')
    # ### end Alembic commands ###
