"""alter pincode length in mapping table

Revision ID: ef1ed10347bb
Revises: 6feab77e43d4
Create Date: 2026-07-05 13:18:40.631765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1ed10347bb'
down_revision: Union[str, Sequence[str], None] = '6feab77e43d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pincode_city_state_mapping_table', 'pincode',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pincode_city_state_mapping_table', 'pincode',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###
