"""add pincode to user_sessions

Revision ID: f4109253d3b9
Revises: i5d6e7f8g9h0
Create Date: 2026-07-05 12:59:37.158857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4109253d3b9'
down_revision: Union[str, Sequence[str], None] = 'i5d6e7f8g9h0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_cart_items_session_id'), table_name='pre_cart_items')
    op.add_column('user_sessions', sa.Column('pincode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'pincode')
    op.create_index(op.f('ix_pre_cart_items_session_id'), 'pre_cart_items', ['session_id'], unique=False)
    # ### end Alembic commands ###
