OCCASION_TYPES = {
    "oc_1": "Daily wear",
    "oc_2": "Office / work",
    "oc_3": "Client meeting / formal business setting",
    "oc_4": "Interview",
    "oc_5": "College / classes",
    "oc_6": "Casual daytime outing",
    "oc_7": "Brunch / café / daytime social setting",
    "oc_8": "Running errands",
    "oc_9": "Gym / workout",
    "oc_10": "Post-workout / athleisure",
    "oc_11": "Outdoor activity / sports",
    "oc_12": "Travel / airport / long commute",
    "oc_13": "Road trip",
    "oc_14": "Summer daytime",
    "oc_15": "Monsoon / rainy day",
    "oc_16": "Winter daytime",
    "oc_17": "Evening outing",
    "oc_18": "Dinner",
    "oc_19": "Fine dining",
    "oc_20": "Date night",
    "oc_21": "Romantic evening at home",
    "oc_22": "Party / social night out",
    "oc_23": "Club / nightlife",
    "oc_24": "Wedding guest",
    "oc_25": "Bride / groom special wear",
    "oc_26": "Festival / celebration",
    "oc_27": "Family gathering",
    "oc_28": "Religious / spiritual setting",
    "oc_29": "Lounge / relaxed evening social",
    "oc_30": "House party",
    "oc_31": "Networking event",
    "oc_32": "Creative / artistic event",
    "oc_33": "Fashion event",
    "oc_34": "Photoshoot / content creation",
    "oc_35": "Home / personal comfort wear",
    "oc_36": "Bedtime / sleep-adjacent use",
    "oc_37": "After shower / freshening up",
    "oc_38": "Signature scent / identity scent",
    "oc_39": "Special occasion / milestone",
    "oc_40": "Luxury / black-tie event",
    "oc_41": "Close-contact setting",
    "oc_42": "Hot crowded environment",
    "oc_43": "Cold outdoor environment",
    "oc_44": "High-humidity environment"
}
