PERCEPTION_DESCRIPTORS = {
    "p_1": "Professional",
    "p_2": "Approachable",
    "p_3": "Confident",
    "p_4": "Commanding",
    "p_5": "Effortless",
    "p_6": "Refined",
    "p_7": "Elite",
    "p_8": "Grounded",
    "p_9": "Dependable",
    "p_10": "Mature",
    "p_11": "Youthful",
    "p_12": "Romantic",
    "p_13": "Mysterious",
    "p_14": "Bold",
    "p_15": "Expressive",
    "p_16": "Subtle",
    "p_17": "Fresh",
    "p_18": "Light",
    "p_19": "Energizing",
    "p_20": "Rich",
    "p_21": "Attractive",
    "p_22": "Warm"
}
